drop table "User" cascade;
drop table admin cascade;
drop table art cascade;
drop table artist cascade;
drop table auction cascade;
drop table bid cascade;
drop table cascade;
drop table art__collection cascade;
drop table collector cascade;
drop table notification cascade;
drop table post cascade;
drop table rating cascade;
drop table tag cascade;
drop table tag_junction_art cascade;
drop table collection cascade;
drop table favorite cascade;
drop table report cascade;
drop table tag__post cascade;
drop table tutorial cascade;

