drop table "User" cascade;
drop table admin cascade;
drop table art cascade;
drop table artist cascade;
drop table auction cascade;
drop table bid cascade;
drop table cascade;
drop table collection_art cascade;
drop table collector cascade;
drop table notification cascade;
drop table post cascade;
drop table rating cascade;
drop table tag cascade;
drop table tag_junction_art cascade;
